"""empty message

Revision ID: af7084d3c338
Revises: 
Create Date: 2019-12-12 15:31:56.360344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af7084d3c338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link', 'user', ['user_id'], ['id'])
    op.drop_column('link', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'link',
        sa.Column('user',
                  mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
                  nullable=True))
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_column('link', 'user_id')
    # ### end Alembic commands ###
